import { NextRequest, NextResponse } from 'next/server';
import { checkLimit, proRequiredResponse } from '@/lib/subscription';
import { createClient } from '@supabase/supabase-js';

export async function POST(request: NextRequest) {
  const sb = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co',
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder'
  );
  const { data: { user } } = await sb.auth.getUser();
  if (!user) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });

  const access = await checkLimit(user.id, 'pdf_export');
  if (!access.allowed) return proRequiredResponse('pdf_export');

  const { itinerary } = await request.json();
  if (!itinerary) return NextResponse.json({ error: 'itinerary required' }, { status: 400 });

  try {
    const { Document, Page, Text, View, StyleSheet, Font, renderToBuffer } = await import('@react-pdf/renderer');
    const { createElement: h } = await import('react');

    const styles = StyleSheet.create({
      page: { backgroundColor: '#0A0F1E', padding: 40, fontFamily: 'Helvetica' },
      coverTitle: { fontSize: 42, color: '#F59E0B', marginBottom: 12 },
      coverSub: { fontSize: 18, color: '#E2E8F0', marginBottom: 8 },
      coverMeta: { fontSize: 12, color: '#94A3B8', marginBottom: 4 },
      sectionTitle: { fontSize: 16, color: '#F59E0B', marginBottom: 8, marginTop: 20 },
      dayTheme: { fontSize: 14, color: '#E2E8F0', marginBottom: 6, fontWeight: 'bold' },
      activityName: { fontSize: 11, color: '#E2E8F0', marginBottom: 2 },
      activityDesc: { fontSize: 9, color: '#94A3B8', marginBottom: 6 },
      periodLabel: { fontSize: 10, color: '#F59E0B', marginBottom: 4, marginTop: 8 },
      budgetRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
      budgetLabel: { fontSize: 10, color: '#94A3B8' },
      budgetValue: { fontSize: 10, color: '#E2E8F0' },
      total: { fontSize: 12, color: '#F59E0B', fontWeight: 'bold' },
      footer: { position: 'absolute', bottom: 20, left: 40, right: 40, fontSize: 8, color: '#475569', textAlign: 'center' },
      divider: { borderBottom: '1pt solid #1E293B', marginVertical: 8 },
      packingItem: { fontSize: 9, color: '#94A3B8', marginBottom: 2 },
      tip: { fontSize: 9, color: '#94A3B8', marginBottom: 4 },
    });

    const ts = itinerary.tripSummary;
    const bs = itinerary.budgetSummary;

    const doc = h(Document, {},
      // Cover page
      h(Page, { size: 'A4', style: styles.page },
        h(View, {},
          h(Text, { style: styles.coverTitle }, ts.destination),
          h(Text, { style: styles.coverSub }, ts.country),
          h(Text, { style: styles.coverMeta }, `${ts.duration} days · ${ts.travelStyle} · ${ts.totalTravelers} traveler${ts.totalTravelers > 1 ? 's' : ''}`),
          h(Text, { style: styles.coverMeta }, `Budget: ${bs.currency} ${bs.grandTotal.toLocaleString()}`),
        ),
        h(Text, { style: styles.footer }, 'Generated by Driftplan · driftplan.app'),
      ),
      // Day pages
      ...itinerary.days.map((day: {dayNumber: number; theme: string; morning: {activities: {name: string; description: string}[]}; afternoon: {activities: {name: string; description: string}[]}; evening: {activities: {name: string; description: string}[]}}) =>
        h(Page, { size: 'A4', style: styles.page, key: day.dayNumber },
          h(View, {},
            h(Text, { style: styles.dayTheme }, `Day ${day.dayNumber}: ${day.theme}`),
            h(View, { style: styles.divider }),
            ...(['morning', 'afternoon', 'evening'] as const).flatMap((period) =>
              day[period].activities.length > 0
                ? [
                    h(Text, { style: styles.periodLabel, key: period }, period.charAt(0).toUpperCase() + period.slice(1)),
                    ...day[period].activities.map((act: {name: string; description: string}, i: number) =>
                      h(View, { key: i },
                        h(Text, { style: styles.activityName }, `• ${act.name}`),
                        h(Text, { style: styles.activityDesc }, act.description),
                      )
                    ),
                  ]
                : []
            ),
          ),
          h(Text, { style: styles.footer }, 'Generated by Driftplan · driftplan.app'),
        )
      ),
      // Budget + packing page
      h(Page, { size: 'A4', style: styles.page },
        h(View, {},
          h(Text, { style: styles.sectionTitle }, 'Budget Summary'),
          h(View, { style: styles.budgetRow }, h(Text, { style: styles.budgetLabel }, 'Accommodation'), h(Text, { style: styles.budgetValue }, `${bs.currency} ${bs.accommodation}`)),
          h(View, { style: styles.budgetRow }, h(Text, { style: styles.budgetLabel }, 'Food'), h(Text, { style: styles.budgetValue }, `${bs.currency} ${bs.food}`)),
          h(View, { style: styles.budgetRow }, h(Text, { style: styles.budgetLabel }, 'Activities'), h(Text, { style: styles.budgetValue }, `${bs.currency} ${bs.activities}`)),
          h(View, { style: styles.budgetRow }, h(Text, { style: styles.budgetLabel }, 'Local Transport'), h(Text, { style: styles.budgetValue }, `${bs.currency} ${bs.localTransport}`)),
          h(View, { style: styles.budgetRow }, h(Text, { style: styles.budgetLabel }, 'Flights Est.'), h(Text, { style: styles.budgetValue }, `${bs.currency} ${bs.flightsEstimate}`)),
          h(View, { style: styles.divider }),
          h(View, { style: styles.budgetRow }, h(Text, { style: styles.total }, 'Grand Total'), h(Text, { style: styles.total }, `${bs.currency} ${bs.grandTotal.toLocaleString()}`)),
          h(Text, { style: styles.sectionTitle }, 'Packing Essentials'),
          ...itinerary.packingList.essentials.map((item: string, i: number) => h(Text, { style: styles.packingItem, key: i }, `• ${item}`)),
          h(Text, { style: styles.sectionTitle }, 'Local Tips'),
          ...itinerary.localTips.slice(0, 5).map((tip: string, i: number) => h(Text, { style: styles.tip, key: i }, `→ ${tip}`)),
        ),
        h(Text, { style: styles.footer }, 'Generated by Driftplan · driftplan.app'),
      )
    );

    const buffer = await renderToBuffer(doc);
    const base64 = buffer.toString('base64');

    return NextResponse.json({ pdf: base64, filename: `driftplan-${ts.destination.toLowerCase().replace(/\s+/g, '-')}.pdf` });
  } catch (err) {
    console.error('[export] PDF generation error:', err);
    return NextResponse.json({ error: 'pdf_generation_failed' }, { status: 500 });
  }
}
